# Generated by Django 5.1.15 on 2026-03-01 21:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('default_risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('ultra_high', 'Ultra High')], default='low', max_length=20)),
            ],
            options={
                'verbose_name': 'Activity Catalog',
                'verbose_name_plural': 'Activity Catalog',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EntityActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(max_length=100)),
                ('country_risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('ultra_high', 'Ultra High')], default='low', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('ultra_high', 'Ultra High')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_activities', to='core.activitycatalog')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.entity')),
            ],
            options={
                'verbose_name': 'Entity Activity',
                'verbose_name_plural': 'Entity Activities',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EntityOfficer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(choices=[('director', 'Director'), ('president', 'President'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('registered_agent', 'Registered Agent'), ('protector', 'Protector'), ('authorized_signatory', 'Authorized Signatory'), ('other', 'Other')], max_length=30)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='core.entity')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officer_positions', to='core.person')),
            ],
            options={
                'verbose_name': 'Entity Officer',
                'verbose_name_plural': 'Entity Officers',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShareClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('par_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('authorized_shares', models.IntegerField(blank=True, null=True)),
                ('voting_rights', models.BooleanField(default=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_classes', to='core.entity')),
            ],
            options={
                'verbose_name': 'Share Class',
                'verbose_name_plural': 'Share Classes',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SourceOfFunds',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('ultra_high', 'Ultra High')], default='low', max_length=20)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources_of_funds', to='core.entity')),
            ],
            options={
                'verbose_name': 'Source of Funds',
                'verbose_name_plural': 'Sources of Funds',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SourceOfWealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('ultra_high', 'Ultra High')], default='low', max_length=20)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources_of_wealth', to='core.person')),
            ],
            options={
                'verbose_name': 'Source of Wealth',
                'verbose_name_plural': 'Sources of Wealth',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShareIssuance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('num_shares', models.IntegerField()),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('certificate_number', models.CharField(blank=True, default='', max_length=50)),
                ('is_jtwros', models.BooleanField(default=False)),
                ('jtwros_partner_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_trustee', models.BooleanField(default=False)),
                ('trustee_for', models.CharField(blank=True, default='', max_length=255)),
                ('share_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuances', to='core.shareclass')),
                ('shareholder_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_issuances_as_holder', to='core.entity')),
                ('shareholder_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_issuances', to='core.person')),
            ],
            options={
                'verbose_name': 'Share Issuance',
                'verbose_name_plural': 'Share Issuances',
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('shareholder_entity__isnull', True), ('shareholder_person__isnull', False)), models.Q(('shareholder_entity__isnull', False), ('shareholder_person__isnull', True)), _connector='OR'), name='share_issuance_holder_xor')],
            },
        ),
    ]
