# Generated by Django 5.1.15 on 2026-03-02 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seed_source_of_funds_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceoffunds',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_sources', to='core.sourceoffundscatalog'),
        ),
    ]
