# Generated by Django 5.1.15 on 2026-03-09 13:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_entity_audit_and_kyc_changes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_approval', max_length=20),
        ),
        migrations.CreateModel(
            name='PersonAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(max_length=50)),
                ('record_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(choices=[('internal', 'Internal Edit'), ('guest_submission', 'Guest Submission'), ('approval', 'Approval'), ('send_back', 'Send Back')], max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.person')),
            ],
            options={
                'verbose_name': 'Person Audit Log',
                'verbose_name_plural': 'Person Audit Logs',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['person', '-created_at'], name='idx_audit_person_created')],
            },
        ),
    ]
