# Generated by Django 5.1.15 on 2026-03-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_person_status_audit_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
