# Generated by Django 5.1.15 on 2026-03-01 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('compliance', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestlink',
            name='kyc_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_links', to='compliance.kycsubmission'),
        ),
        migrations.AddField(
            model_name='guestlink',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_links', to='workflow.ticket'),
        ),
        migrations.AddConstraint(
            model_name='guestlink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kyc_submission__isnull', True), ('ticket__isnull', False)), models.Q(('kyc_submission__isnull', False), ('ticket__isnull', True)), _connector='OR'), name='guest_link_exactly_one_target'),
        ),
    ]
