# Generated by Django 5.2.3 on 2026-03-11 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_add_magic_login_token'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='guestlink',
            name='guest_link_exactly_one_target',
        ),
    ]
