# Generated by Django 5.2.3 on 2026-03-11 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_guestlink_guest_link_exactly_one_target'),
        ('compliance', '0007_accountingrecord_accountingrecorddocument_and_more'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestlink',
            name='accounting_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_links', to='compliance.accountingrecord'),
        ),
        migrations.AddConstraint(
            model_name='guestlink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('accounting_record__isnull', True), ('kyc_submission__isnull', True), ('ticket__isnull', False)), models.Q(('accounting_record__isnull', True), ('kyc_submission__isnull', False), ('ticket__isnull', True)), models.Q(('accounting_record__isnull', False), ('kyc_submission__isnull', True), ('ticket__isnull', True)), _connector='OR'), name='guest_link_exactly_one_target'),
        ),
    ]
