# Generated by Django 5.1.15 on 2026-03-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_guestlink_es_submission'),
        ('compliance', '0010_phase3_models'),
        ('workflow', '0004_add_state_unique_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='guestlink',
            name='guest_link_exactly_one_target',
        ),
        migrations.AddConstraint(
            model_name='guestlink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('accounting_record__isnull', True), ('es_submission__isnull', True), ('kyc_submission__isnull', True), ('ticket__isnull', False)), models.Q(('accounting_record__isnull', True), ('es_submission__isnull', True), ('kyc_submission__isnull', False), ('ticket__isnull', True)), models.Q(('accounting_record__isnull', False), ('es_submission__isnull', True), ('kyc_submission__isnull', True), ('ticket__isnull', True)), models.Q(('accounting_record__isnull', True), ('es_submission__isnull', False), ('kyc_submission__isnull', True), ('ticket__isnull', True)), _connector='OR'), name='guest_link_exactly_one_target'),
        ),
    ]
