export interface Country {
  code: string;
  name: string;
}

export const COUNTRIES: Country[] = [
  { code: "PA", name: "Panamá" },
  { code: "US", name: "Estados Unidos" },
  { code: "CO", name: "Colombia" },
  { code: "CR", name: "Costa Rica" },
  { code: "MX", name: "México" },
  { code: "BR", name: "Brasil" },
  { code: "AR", name: "Argentina" },
  { code: "CL", name: "Chile" },
  { code: "PE", name: "Perú" },
  { code: "EC", name: "Ecuador" },
  { code: "VE", name: "Venezuela" },
  { code: "DO", name: "República Dominicana" },
  { code: "GT", name: "Guatemala" },
  { code: "HN", name: "Honduras" },
  { code: "SV", name: "El Salvador" },
  { code: "NI", name: "Nicaragua" },
  { code: "BZ", name: "Belice" },
  { code: "UY", name: "Uruguay" },
  { code: "PY", name: "Paraguay" },
  { code: "BO", name: "Bolivia" },
  { code: "ES", name: "España" },
  { code: "GB", name: "Reino Unido" },
  { code: "FR", name: "Francia" },
  { code: "DE", name: "Alemania" },
  { code: "IT", name: "Italia" },
  { code: "CH", name: "Suiza" },
  { code: "NL", name: "Países Bajos" },
  { code: "CA", name: "Canadá" },
  { code: "CN", name: "China" },
  { code: "JP", name: "Japón" },
  { code: "KR", name: "Corea del Sur" },
  { code: "AU", name: "Australia" },
  { code: "NZ", name: "Nueva Zelanda" },
  { code: "SG", name: "Singapur" },
  { code: "HK", name: "Hong Kong" },
  { code: "AE", name: "Emiratos Árabes Unidos" },
  { code: "IL", name: "Israel" },
  { code: "ZA", name: "Sudáfrica" },
  { code: "VG", name: "Islas Vírgenes Británicas" },
  { code: "KY", name: "Islas Caimán" },
  { code: "BM", name: "Bermudas" },
  { code: "BS", name: "Bahamas" },
  { code: "BB", name: "Barbados" },
  { code: "TT", name: "Trinidad y Tobago" },
  { code: "JM", name: "Jamaica" },
  { code: "CU", name: "Cuba" },
  { code: "PR", name: "Puerto Rico" },
  { code: "PT", name: "Portugal" },
  { code: "IE", name: "Irlanda" },
  { code: "LU", name: "Luxemburgo" },
  { code: "AT", name: "Austria" },
  { code: "BE", name: "Bélgica" },
  { code: "SE", name: "Suecia" },
  { code: "NO", name: "Noruega" },
  { code: "DK", name: "Dinamarca" },
  { code: "FI", name: "Finlandia" },
  { code: "IN", name: "India" },
  { code: "TW", name: "Taiwán" },
  { code: "TH", name: "Tailandia" },
  { code: "MY", name: "Malasia" },
  { code: "PH", name: "Filipinas" },
  { code: "ID", name: "Indonesia" },
  { code: "RU", name: "Rusia" },
  { code: "TR", name: "Turquía" },
  { code: "SA", name: "Arabia Saudita" },
  { code: "EG", name: "Egipto" },
  { code: "NG", name: "Nigeria" },
  { code: "KE", name: "Kenia" },
  { code: "GH", name: "Ghana" },
];
