# Generated by Django 5.1.15 on 2026-03-14 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0012_riskassessment_riskassess_entity_current_idx_and_more'),
        ('core', '0017_entity_ubo_exception_type'),
        ('workflow', '0004_add_state_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ticket Log', 'verbose_name_plural': 'Ticket Logs'},
        ),
        migrations.RemoveField(
            model_name='ticketlog',
            name='timestamp',
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['current_state'], name='ticket_current_state_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_to'], name='ticket_assigned_to_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['client'], name='ticket_client_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['entity'], name='ticket_entity_idx'),
        ),
    ]
