# Generated by Django 5.1.15 on 2026-03-01 18:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='templates/')),
                ('entity_type', models.CharField(blank=True, default='', help_text="E.g. 'corporation', 'trust', 'foundation'", max_length=50)),
                ('jurisdiction', models.CharField(blank=True, default='', help_text="E.g. 'bvi', 'panama'", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Document Template',
                'verbose_name_plural': 'Document Templates',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_file', models.FileField(upload_to='generated/')),
                ('format', models.CharField(choices=[('docx', 'DOCX'), ('pdf', 'PDF')], default='docx', max_length=10)),
                ('sharepoint_file_id', models.CharField(blank=True, default='', help_text='SharePoint file ID for PDF archival', max_length=255)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='documents.documenttemplate')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='workflow.ticket')),
            ],
            options={
                'verbose_name': 'Generated Document',
                'verbose_name_plural': 'Generated Documents',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
