# Generated by Django 5.1.15 on 2026-03-01 18:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JurisdictionRisk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_code', models.CharField(max_length=3, unique=True)),
                ('country_name', models.CharField(max_length=100)),
                ('risk_weight', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
            options={
                'verbose_name': 'Jurisdiction Risk',
                'verbose_name_plural': 'Jurisdiction Risks',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskRecalculationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_id', models.UUIDField(default=uuid.uuid4)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_entities', models.IntegerField(default=0)),
                ('recalculated_count', models.IntegerField(default=0)),
                ('changed_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('triggered_by', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Risk Recalculation Log',
                'verbose_name_plural': 'Risk Recalculation Logs',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KYCSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kyc_submissions', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_submissions', to='workflow.ticket')),
            ],
            options={
                'verbose_name': 'KYC Submission',
                'verbose_name_plural': 'KYC Submissions',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party_type', models.CharField(choices=[('natural', 'Natural'), ('corporate', 'Corporate')], max_length=20)),
                ('role', models.CharField(choices=[('ubo', 'UBO'), ('director', 'Director'), ('shareholder', 'Shareholder'), ('protector', 'Protector'), ('authorized_signatory', 'Authorized Signatory')], max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('nationality', models.CharField(blank=True, default='', max_length=100)),
                ('country_of_residence', models.CharField(blank=True, default='', max_length=100)),
                ('pep_status', models.BooleanField(default=False)),
                ('ownership_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('identification_number', models.CharField(blank=True, default='', max_length=100)),
                ('kyc_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='compliance.kycsubmission')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_parties', to='core.person')),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('cedula', 'Cedula'), ('utility_bill', 'Utility Bill'), ('corporate_registry', 'Corporate Registry'), ('proof_of_address', 'Proof of Address'), ('source_of_wealth', 'Source of Wealth'), ('other', 'Other')], max_length=30)),
                ('original_filename', models.CharField(max_length=255)),
                ('sharepoint_file_id', models.CharField(blank=True, default='', max_length=255)),
                ('sharepoint_web_url', models.URLField(blank=True, default='', max_length=1024)),
                ('sharepoint_drive_item_id', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.IntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('llm_extraction_json', models.JSONField(default=dict)),
                ('llm_extraction_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('kyc_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='compliance.kycsubmission')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='compliance.party')),
            ],
            options={
                'verbose_name': 'Document Upload',
                'verbose_name_plural': 'Document Uploads',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RFI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_fields', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('responded', 'Responded'), ('closed', 'Closed')], default='open', max_length=20)),
                ('response_text', models.TextField(blank=True, default='')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('kyc_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfis', to='compliance.kycsubmission')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_rfis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RFI',
                'verbose_name_plural': 'RFIs',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_score', models.IntegerField()),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('breakdown_json', models.JSONField(default=dict)),
                ('is_current', models.BooleanField(default=True)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto'), ('scheduled', 'Scheduled'), ('webhook', 'Webhook')], max_length=20)),
                ('kyc_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='compliance.kycsubmission')),
            ],
            options={
                'verbose_name': 'Risk Assessment',
                'verbose_name_plural': 'Risk Assessments',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorldCheckCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_system_id', models.CharField(blank=True, default='', max_length=255)),
                ('screening_status', models.CharField(choices=[('pending', 'Pending'), ('clear', 'Clear'), ('matched', 'Matched'), ('false_positive', 'False Positive'), ('true_match', 'True Match'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('last_screened_at', models.DateTimeField(blank=True, null=True)),
                ('ongoing_monitoring_enabled', models.BooleanField(default=False)),
                ('match_data_json', models.JSONField(default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worldcheck_cases', to='compliance.party')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_worldcheck_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'World-Check Case',
                'verbose_name_plural': 'World-Check Cases',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
