# Generated by Django 5.1.15 on 2026-03-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_populate_jurisdictionrisk'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycsubmission',
            name='field_comments',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='proposed_entity_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('sent_back', 'Sent Back')], default='draft', max_length=20),
        ),
    ]
