"""Data migration to add all world countries to JurisdictionRisk.

Uses ignore_conflicts=True so existing entries keep their current risk_weight.
Only new countries are inserted.
"""

from django.db import migrations


# Complete list of ISO 3166-1 countries/territories with alpha-3 codes.
# Risk weights (1-10) based on FATF evaluations, AML frameworks, and
# sanctions lists. Countries already in 0002 will be skipped via
# ignore_conflicts.
ALL_COUNTRIES = [
    # ── Africa ────────────────────────────────────────────────────────
    ("DZA", "Algeria", 6),
    ("AGO", "Angola", 6),
    ("BEN", "Benin", 5),
    ("BWA", "Botswana", 4),
    ("BFA", "Burkina Faso", 6),
    ("BDI", "Burundi", 7),
    ("CPV", "Cape Verde", 4),
    ("CMR", "Cameroon", 7),
    ("CAF", "Central African Republic", 8),
    ("TCD", "Chad", 7),
    ("COM", "Comoros", 6),
    ("COG", "Republic of the Congo", 6),
    ("COD", "Democratic Republic of the Congo", 7),
    ("CIV", "Cote d'Ivoire", 6),
    ("DJI", "Djibouti", 6),
    ("EGY", "Egypt", 6),
    ("GNQ", "Equatorial Guinea", 7),
    ("ERI", "Eritrea", 8),
    ("SWZ", "Eswatini", 5),
    ("ETH", "Ethiopia", 6),
    ("GAB", "Gabon", 5),
    ("GMB", "Gambia", 6),
    ("GHA", "Ghana", 5),
    ("GIN", "Guinea", 6),
    ("GNB", "Guinea-Bissau", 7),
    ("KEN", "Kenya", 7),
    ("LSO", "Lesotho", 5),
    ("LBR", "Liberia", 7),
    ("LBY", "Libya", 9),
    ("MDG", "Madagascar", 6),
    ("MWI", "Malawi", 5),
    ("MLI", "Mali", 7),
    ("MRT", "Mauritania", 6),
    ("MUS", "Mauritius", 4),
    ("MAR", "Morocco", 5),
    ("MOZ", "Mozambique", 7),
    ("NAM", "Namibia", 4),
    ("NER", "Niger", 6),
    ("NGA", "Nigeria", 7),
    ("RWA", "Rwanda", 5),
    ("STP", "Sao Tome and Principe", 5),
    ("SEN", "Senegal", 5),
    ("SYC", "Seychelles", 4),
    ("SLE", "Sierra Leone", 7),
    ("SOM", "Somalia", 9),
    ("ZAF", "South Africa", 6),
    ("SSD", "South Sudan", 8),
    ("SDN", "Sudan", 8),
    ("TZA", "Tanzania", 7),
    ("TGO", "Togo", 6),
    ("TUN", "Tunisia", 5),
    ("UGA", "Uganda", 6),
    ("ZMB", "Zambia", 5),
    ("ZWE", "Zimbabwe", 7),

    # ── Americas ──────────────────────────────────────────────────────
    ("ATG", "Antigua and Barbuda", 5),
    ("ARG", "Argentina", 4),
    ("BHS", "Bahamas", 5),
    ("BRB", "Barbados", 4),
    ("BLZ", "Belize", 6),
    ("BOL", "Bolivia", 5),
    ("BRA", "Brazil", 4),
    ("CAN", "Canada", 2),
    ("CHL", "Chile", 3),
    ("COL", "Colombia", 5),
    ("CRI", "Costa Rica", 4),
    ("CUB", "Cuba", 8),
    ("DMA", "Dominica", 5),
    ("DOM", "Dominican Republic", 5),
    ("ECU", "Ecuador", 5),
    ("SLV", "El Salvador", 5),
    ("GRD", "Grenada", 5),
    ("GTM", "Guatemala", 6),
    ("GUY", "Guyana", 5),
    ("HTI", "Haiti", 7),
    ("HND", "Honduras", 6),
    ("JAM", "Jamaica", 5),
    ("MEX", "Mexico", 4),
    ("NIC", "Nicaragua", 6),
    ("PAN", "Panama", 6),
    ("PRY", "Paraguay", 6),
    ("PER", "Peru", 5),
    ("KNA", "Saint Kitts and Nevis", 5),
    ("LCA", "Saint Lucia", 5),
    ("VCT", "Saint Vincent and the Grenadines", 5),
    ("SUR", "Suriname", 6),
    ("TTO", "Trinidad and Tobago", 5),
    ("USA", "United States", 2),
    ("URY", "Uruguay", 3),
    ("VEN", "Venezuela", 8),

    # ── Asia ──────────────────────────────────────────────────────────
    ("AFG", "Afghanistan", 9),
    ("ARM", "Armenia", 5),
    ("AZE", "Azerbaijan", 5),
    ("BHR", "Bahrain", 5),
    ("BGD", "Bangladesh", 6),
    ("BTN", "Bhutan", 4),
    ("BRN", "Brunei", 4),
    ("KHM", "Cambodia", 6),
    ("CHN", "China", 5),
    ("CYP", "Cyprus", 4),
    ("GEO", "Georgia", 4),
    ("IND", "India", 5),
    ("IDN", "Indonesia", 5),
    ("IRN", "Iran", 10),
    ("IRQ", "Iraq", 8),
    ("ISR", "Israel", 3),
    ("JPN", "Japan", 2),
    ("JOR", "Jordan", 5),
    ("KAZ", "Kazakhstan", 4),
    ("KWT", "Kuwait", 5),
    ("KGZ", "Kyrgyzstan", 5),
    ("LAO", "Laos", 6),
    ("LBN", "Lebanon", 6),
    ("MYS", "Malaysia", 3),
    ("MDV", "Maldives", 5),
    ("MNG", "Mongolia", 7),
    ("MMR", "Myanmar", 9),
    ("NPL", "Nepal", 5),
    ("PRK", "North Korea", 10),
    ("OMN", "Oman", 5),
    ("PAK", "Pakistan", 7),
    ("PSE", "Palestine", 6),
    ("PHL", "Philippines", 6),
    ("QAT", "Qatar", 5),
    ("SAU", "Saudi Arabia", 5),
    ("SGP", "Singapore", 3),
    ("KOR", "South Korea", 3),
    ("LKA", "Sri Lanka", 5),
    ("SYR", "Syria", 9),
    ("TWN", "Taiwan", 3),
    ("TJK", "Tajikistan", 6),
    ("THA", "Thailand", 5),
    ("TLS", "Timor-Leste", 5),
    ("TKM", "Turkmenistan", 6),
    ("ARE", "United Arab Emirates", 5),
    ("UZB", "Uzbekistan", 5),
    ("VNM", "Vietnam", 7),
    ("YEM", "Yemen", 9),

    # ── Europe ────────────────────────────────────────────────────────
    ("ALB", "Albania", 5),
    ("AND", "Andorra", 3),
    ("AUT", "Austria", 1),
    ("BLR", "Belarus", 7),
    ("BEL", "Belgium", 2),
    ("BIH", "Bosnia and Herzegovina", 5),
    ("BGR", "Bulgaria", 4),
    ("HRV", "Croatia", 3),
    ("CZE", "Czech Republic", 2),
    ("DNK", "Denmark", 1),
    ("EST", "Estonia", 2),
    ("FIN", "Finland", 1),
    ("FRA", "France", 2),
    ("DEU", "Germany", 1),
    ("GRC", "Greece", 3),
    ("HUN", "Hungary", 2),
    ("ISL", "Iceland", 1),
    ("IRL", "Ireland", 2),
    ("ITA", "Italy", 2),
    ("XKX", "Kosovo", 5),
    ("LVA", "Latvia", 2),
    ("LIE", "Liechtenstein", 3),
    ("LTU", "Lithuania", 2),
    ("LUX", "Luxembourg", 2),
    ("MLT", "Malta", 4),
    ("MDA", "Moldova", 5),
    ("MCO", "Monaco", 3),
    ("MNE", "Montenegro", 4),
    ("NLD", "Netherlands", 1),
    ("MKD", "North Macedonia", 5),
    ("NOR", "Norway", 1),
    ("POL", "Poland", 2),
    ("PRT", "Portugal", 2),
    ("ROU", "Romania", 4),
    ("RUS", "Russia", 8),
    ("SMR", "San Marino", 3),
    ("SRB", "Serbia", 4),
    ("SVK", "Slovakia", 2),
    ("SVN", "Slovenia", 2),
    ("ESP", "Spain", 2),
    ("SWE", "Sweden", 1),
    ("CHE", "Switzerland", 2),
    ("UKR", "Ukraine", 4),
    ("GBR", "United Kingdom", 2),
    ("VAT", "Vatican City", 2),

    # ── Oceania ───────────────────────────────────────────────────────
    ("AUS", "Australia", 2),
    ("FJI", "Fiji", 4),
    ("KIR", "Kiribati", 5),
    ("MHL", "Marshall Islands", 5),
    ("FSM", "Micronesia", 5),
    ("NRU", "Nauru", 6),
    ("NZL", "New Zealand", 1),
    ("PLW", "Palau", 5),
    ("PNG", "Papua New Guinea", 6),
    ("WSM", "Samoa", 5),
    ("SLB", "Solomon Islands", 5),
    ("TON", "Tonga", 5),
    ("TUV", "Tuvalu", 5),
    ("VUT", "Vanuatu", 6),

    # ── Caribbean / Overseas Territories ──────────────────────────────
    ("AIA", "Anguilla", 5),
    ("ABW", "Aruba", 4),
    ("BMU", "Bermuda", 5),
    ("VGB", "British Virgin Islands", 6),
    ("CYM", "Cayman Islands", 5),
    ("CUW", "Curacao", 4),
    ("GLP", "Guadeloupe", 3),
    ("MTQ", "Martinique", 3),
    ("MSR", "Montserrat", 5),
    ("PRI", "Puerto Rico", 3),
    ("BLM", "Saint Barthelemy", 3),
    ("MAF", "Saint Martin", 4),
    ("SXM", "Sint Maarten", 4),
    ("TCA", "Turks and Caicos Islands", 5),
    ("VIR", "US Virgin Islands", 3),

    # ── Other Territories ─────────────────────────────────────────────
    ("HKG", "Hong Kong", 5),
    ("MAC", "Macau", 5),
    ("GIB", "Gibraltar", 3),
    ("GGY", "Guernsey", 3),
    ("IMN", "Isle of Man", 3),
    ("JEY", "Jersey", 3),
    ("REU", "Reunion", 3),
    ("GUF", "French Guiana", 3),
    ("PYF", "French Polynesia", 3),
    ("NCL", "New Caledonia", 3),
    ("WLF", "Wallis and Futuna", 3),
    ("SPM", "Saint Pierre and Miquelon", 3),
    ("MYT", "Mayotte", 3),
    ("FLK", "Falkland Islands", 3),
    ("SHN", "Saint Helena", 3),
    ("CCK", "Cocos Islands", 3),
    ("CXR", "Christmas Island", 3),
    ("NFK", "Norfolk Island", 3),
    ("COK", "Cook Islands", 5),
    ("NIU", "Niue", 5),
    ("TKL", "Tokelau", 5),
    ("GUM", "Guam", 3),
    ("ASM", "American Samoa", 3),
    ("MNP", "Northern Mariana Islands", 3),
]


def populate_all_countries(apps, schema_editor):
    JurisdictionRisk = apps.get_model("compliance", "JurisdictionRisk")
    objs = [
        JurisdictionRisk(
            country_code=code,
            country_name=name,
            risk_weight=weight,
        )
        for code, name, weight in ALL_COUNTRIES
    ]
    JurisdictionRisk.objects.bulk_create(objs, ignore_conflicts=True)


def reverse_noop(apps, schema_editor):
    """No-op reverse — we don't remove countries added by this migration."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0005_seed_risk_matrix_defaults"),
    ]

    operations = [
        migrations.RunPython(
            populate_all_countries,
            reverse_code=reverse_noop,
        ),
    ]
