# Generated by Django 5.2.3 on 2026-03-11 23:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0006_populate_all_countries'),
        ('core', '0016_entity_nominal_directors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_year', models.IntegerField(default=2025)),
                ('form_type', models.CharField(blank=True, choices=[('no_operations', 'Sociedad sin operaciones'), ('panama_assets', 'Activos solo en Panamá'), ('balance_general', 'Balance general'), ('exempt_license', 'Exento por aviso de operación')], default='', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('signature_data', models.TextField(blank=True, default='')),
                ('signer_name', models.CharField(blank=True, default='', max_length=255)),
                ('signer_identification', models.CharField(blank=True, default='', max_length=100)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_records', to='core.entity')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_accounting_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accounting Record',
                'verbose_name_plural': 'Accounting Records',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountingRecordDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='accounting_records/%Y/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('accounting_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='compliance.accountingrecord')),
            ],
            options={
                'verbose_name': 'Accounting Record Document',
                'verbose_name_plural': 'Accounting Record Documents',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='accountingrecord',
            constraint=models.UniqueConstraint(fields=('entity', 'fiscal_year'), name='unique_accounting_record_per_entity_year'),
        ),
    ]
