# Generated by Django 5.1.15 on 2026-03-12 02:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0007_accountingrecord_accountingrecorddocument_and_more'),
        ('core', '0016_entity_nominal_directors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accountingrecord',
            index=models.Index(fields=['fiscal_year', 'status'], name='accrec_fy_status_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingrecord',
            index=models.Index(fields=['entity', 'fiscal_year'], name='accrec_entity_fy_idx'),
        ),
    ]
