# Generated by Django 5.1.15 on 2026-03-14 19:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0010_phase3_models'),
        ('core', '0017_entity_ubo_exception_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingrecord',
            name='form_type',
            field=models.CharField(blank=True, choices=[('no_operations', 'Sociedad sin operaciones'), ('panama_assets', 'Formulario B - Tenedora de activos'), ('balance_general', 'Balance general'), ('exempt_license', 'Exento por aviso de operación')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='ComplianceDelegation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(choices=[('accounting_records', 'Accounting Records'), ('economic_substance', 'Economic Substance'), ('kyc', 'KYC')], max_length=30)),
                ('fiscal_year', models.IntegerField(default=2025)),
                ('delegate_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('delegate_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegations_received', to=settings.AUTH_USER_MODEL)),
                ('delegated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_created', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='core.entity')),
            ],
            options={
                'verbose_name': 'Compliance Delegation',
                'verbose_name_plural': 'Compliance Delegations',
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'accepted'])), fields=('entity', 'module', 'fiscal_year', 'delegate_email'), name='unique_active_delegation')],
            },
        ),
    ]
