# Generated by Django 5.1.15 on 2026-03-14 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0011_alter_accountingrecord_form_type_and_more'),
        ('core', '0017_entity_ubo_exception_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['entity', 'is_current'], name='riskassess_entity_current_idx'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['person', 'is_current'], name='riskassess_person_current_idx'),
        ),
    ]
